@startjson Hub Contact Record
{
    "id": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
    "title": "Mr",
    "firstName": "Anthony",
    "lastName": "Payne",
    "formalSalutation": "Sir",
    "semiformalSalutation": "Mr Payne",
    "informalSalutation": "Anthony",
    "personalSalutation": null,
    "envelopeSalutation": "Mr Anthony Payne",
    "defaultSalutationId": "584f1d04-e1f7-45f8-a1f7-5de9ec11930a",
    "negotiators": [
        {
            "id": "da7acf31-c285-ea11-a958-000d3ab2efee",
            "user": {
                "id": "eb52e446-d51e-4c97-8fca-07603e530042",
                "firstName": "John",
                "lastName": "Rockel",
                "departmentId": "92757eed-a211-4e67-b9c9-245fda672ef8",
                "department": {
                    "id": "92757eed-a211-4e67-b9c9-245fda672ef8",
                    "name": "Residential Operations & Strategy"
                },
                "business": {
                    "id": "810ae70d-3d0d-e611-82fe-501ac503c095",
                    "name": "Knight Frank LLP"
                },
                "emailAddress": "john.rockel@knightfrank.com",
                "divisionId": "2d4c1d04-e1f7-45f8-a1f7-5de9ec11930a",
                "division": {
                    "id": "2d4c1d04-e1f7-45f8-a1f7-5de9ec11930a",
                    "code": "BusinessServices",
                    "enumTypeId": "174b1d04-e1f7-45f8-a1f7-5de9ec11930a"
                },
                "telephoneNumber": "+44 20 7861 1684",
                "mobileNumber": "+44 7747 007 826",
                "employeeNumber": "00000374",
                "countryId": "714a1d04-e1f7-45f8-a1f7-5de9ec11930a",
                "jobRole": "Partner, Head of Strategy & Operations",
                "active": true,
                "callbackFrequencyId": null,
                "isConfirmedByAttendee": null
            },
            "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
            "relationshipTypeId": null,
            "isKeyRelationship": false,
            "keyRelationshipStatement": null,
            "isTargetRelationship": false,
            "targetRelationshipStatement": null,
            "userId": "eb52e446-d51e-4c97-8fca-07603e530042",
            "callDate": null,
            "callbackReasonId": null,
            "callbackReasonOther": null,
            "willFadeDate": null,
            "fadedDate": null
        }
    ],
    "companiesContacts": [
        {
            "companyBranch": null,
            "jobTitle": null,
            "contact": {
                "contactPhones": [
                    {
                        "id": "3f15921f-b544-ea11-90fa-005056822d53",
                        "number": "+44 2079246622",
                        "description": "",
                        "isPrimary": true,
                        "phoneTypeCode": "PhoneTypeBusiness",
                        "phoneTypeId": "f04f1d04-e1f7-45f8-a1f7-5de9ec11930a",
                        "lastWriteTime": "2024-05-09T09:06:02.338Z"
                    },
                    {
                        "id": "da34921f-b544-ea11-90fa-005056822d53",
                        "number": "+44 7785725035",
                        "description": "",
                        "isPrimary": true,
                        "phoneTypeCode": "PhoneTypeMobile",
                        "phoneTypeId": "f14f1d04-e1f7-45f8-a1f7-5de9ec11930a",
                        "lastWriteTime": "2024-05-09T09:06:02.338Z"
                    }
                ],
                "id": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
                "title": "Mr",
                "firstName": "Anthony",
                "lastName": "Payne",
                "cddWarningFlag": false,
                "isDeceased": false,
                "isProspect": false,
                "isLockedToNegotiators": false,
                "agreementName": "Mr Anthony Payne",
                "primaryEmail": null,
                "contactEmails": [
                    {
                        "id": "0ef9a42f-b444-ea11-90fa-005056822d53",
                        "email": "anthony@lonres.com",
                        "description": "",
                        "isPrimary": true,
                        "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
                        "myKfInviteDate": null,
                        "myKfAccountStatusId": null,
                        "myKfAccountStatus": null,
                        "lastWriteTime": "2022-06-18T18:50:26.013Z",
                        "consentMethodId": null,
                        "directMarketingConsentId": null,
                        "isDomainPrivate": false
                    }
                ],
                "visibilityLevel": 0,
                "semiformalSalutation": "Mr Payne",
                "personalWealthId": "094d1d04-e1f7-45f8-a1f7-5de9ec11930a",
                "contactPortalAccounts": [
                    {
                        "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
                        "accountId": "256c0d08-2608-4700-8ab9-f5dcea979bfc",
                        "portalAccountName": "Abigail Carter",
                        "email": "anthony@lonres.com",
                        "createdByUserId": "a220a1ff-8c6e-d242-8151-f653de81fcc3",
                        "accountTypeId": "940bd388-2d0e-4c8e-bd71-b0a6b4df1aa2",
                        "inviteSentTime": "2024-05-20T08:51:55.122Z",
                        "lastLoginTime": "2024-05-20T09:39:35.948Z",
                        "companyContactPortalAccess": []
                    }
                ]
            },
            "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
            "company": {
                "id": "c30c0fb1-77fa-4932-9f86-63972e2dc023",
                "name": "LonRes Limited",
                "cddWarningFlag": false,
                "owningCompanyName": null,
                "version": 981,
                "valid": true,
                "websiteUrl": "http://www.lonres.com",
                "description": "LonRes \r\nFirst Floor, 37 Battersea Square, \r\nLondon SW11 3RA",
                "clientCarePageUrl": "",
                "companyTypeId": null,
                "companyCategoryId": "c04c1d04-e1f7-45f8-a1f7-5de9ec11930a",
                "clientCareStatusId": null,
                "relationshipManagerId": null,
                "owningCompanyId": null,
                "registrationNumber": null,
                "email": null,
                "agreementName": null,
                "tenantTypeId": null,
                "tenantSubTypeId": null,
                "investorTypeId": null,
                "headOfficeLocationId": null,
                "portalSetupTime": null,
                "isVerifiedKFEntity": null,
                "isKFChildEntity": null
            },
            "companyId": "c30c0fb1-77fa-4932-9f86-63972e2dc023",
            "address": null,
            "isPrimary": false,
            "visibilityLevel": 0,
            "partyRoleTypeId": null,
            "hasCompanyPortalAccount": false
        }
    ],
    "nationalityId": "cdf904da-2e7e-e911-a816-000d3ab8dca4",
    "isPodDoNotCall": false,
    "isSuperRichAdvisor": false,
    "superRichProfile": null,
    "importantInformation": null,
    "isSensitive": null,
    "sourceId": "7d2e7889-d1bc-404c-aaad-4d3b3930f996",
    "personalWealthId": "094d1d04-e1f7-45f8-a1f7-5de9ec11930a",
    "propertyInterests": [],
    "contactTypes": [
        {
            "id": "ef2e1342-e30d-ef11-a97b-000d3ab2efee",
            "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
            "enumTypeItemId": "014d1d04-e1f7-45f8-a1f7-5de9ec11930a"
        }
    ],
    "propertyTypeInterests": [],
    "professionId": "e8fa04da-2e7e-e911-a816-000d3ab8dca4",
    "professionText": null,
    "ageBandId": null,
    "approxBirthDate": null,
    "twitterUrl": null,
    "linkedInUrl": null,
    "websiteUrl": null,
    "cddWarningFlag": false,
    "contactRelationships": [],
    "contactPhones": [
        {
            "id": "3f15921f-b544-ea11-90fa-005056822d53",
            "number": "+44 2079246622",
            "description": "",
            "isPrimary": true,
            "phoneTypeCode": "PhoneTypeBusiness",
            "phoneTypeId": "f04f1d04-e1f7-45f8-a1f7-5de9ec11930a",
            "lastWriteTime": "2024-05-09T09:06:02.338Z"
        },
        {
            "id": "da34921f-b544-ea11-90fa-005056822d53",
            "number": "+44 7785725035",
            "description": "",
            "isPrimary": true,
            "phoneTypeCode": "PhoneTypeMobile",
            "phoneTypeId": "f14f1d04-e1f7-45f8-a1f7-5de9ec11930a",
            "lastWriteTime": "2024-05-09T09:06:02.338Z"
        }
    ],
    "contactEmails": [
        {
            "id": "0ef9a42f-b444-ea11-90fa-005056822d53",
            "email": "anthony@lonres.com",
            "description": "",
            "isPrimary": true,
            "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
            "myKfInviteDate": null,
            "myKfAccountStatusId": null,
            "myKfAccountStatus": null,
            "lastWriteTime": "2022-06-18T18:50:26.013Z",
            "consentMethodId": null,
            "directMarketingConsentId": null,
            "isDomainPrivate": false
        }
    ],
    "notes": [
        {
            "id": "507b13d3-4189-ea11-a958-000d3ab2efee",
            "description": "Received 'Thinking of you' lockdown dotmailer.\nThank you for the email but I have now put my plans on hold.\n\nKind regards\n\nAnthony Payne",
            "creationTime": "2020-04-28T11:17:27.081Z",
            "user": {
                "id": "0f931fc5-88ce-4709-aee8-49daaaa2de8a",
                "firstName": "Gemma",
                "lastName": "Stride",
                "departmentId": "9ac6cdbd-40bb-4057-afeb-e0e8daf285ba",
                "department": {
                    "id": "9ac6cdbd-40bb-4057-afeb-e0e8daf285ba",
                    "name": "Haslemere"
                },
                "business": {
                    "id": "810ae70d-3d0d-e611-82fe-501ac503c095",
                    "name": "Knight Frank LLP"
                },
                "emailAddress": "gemma.stride@knightfrank.com",
                "divisionId": "2b4c1d04-e1f7-45f8-a1f7-5de9ec11930a",
                "division": {
                    "id": "2b4c1d04-e1f7-45f8-a1f7-5de9ec11930a",
                    "code": "Residential",
                    "enumTypeId": "174b1d04-e1f7-45f8-a1f7-5de9ec11930a"
                },
                "telephoneNumber": "+44 1428 770 561",
                "mobileNumber": "+44 7890 989 827",
                "employeeNumber": "00005308",
                "countryId": "714a1d04-e1f7-45f8-a1f7-5de9ec11930a",
                "jobRole": "Business Support Coordinator",
                "active": true,
                "callbackFrequencyId": null,
                "isConfirmedByAttendee": null
            },
            "relatedEnumTypeItemId": null,
            "flagLevel": null
        }
    ],
    "contactAddresses": [
        {
            "id": "824bcabc-b8d2-ef11-a889-000d3ab29ae8",
            "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
            "addressId": "7f4bcabc-b8d2-ef11-a889-000d3ab29ae8",
            "isPrimary": false,
            "isCorrespondenceConfidential": false,
            "address": {
                "id": "7f4bcabc-b8d2-ef11-a889-000d3ab29ae8",
                "countryId": "714a1d04-e1f7-45f8-a1f7-5de9ec11930a",
                "addressFormId": "71cf4d03-cdcb-e911-90f5-005056822d53",
                "propertyName": "114A",
                "propertyNumber": "",
                "line1": "",
                "line2": "Warwick Way",
                "line3": "",
                "postcode": "SW1V 1SD",
                "city": "London",
                "county": "",
                "longitude": -0.1436423,
                "latitude": 51.4910069,
                "udprnKey": "23758349",
                "umrrnKey": null,
                "uprnKey": null,
                "shortAddress": "114A, Warwick Way, London, SW1V 1SD",
                "shortAddressFormatted": "114A, Warwick Way, London, SW1V 1SD",
                "visibilityLevel": 0
            },
            "creationTime": "2025-01-14T20:47:16.716Z",
            "contact": {
                "id": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
                "title": "Mr",
                "firstName": "Anthony",
                "lastName": "Payne",
                "cddWarningFlag": false,
                "isDeceased": false,
                "isProspect": false,
                "isLockedToNegotiators": false,
                "agreementName": "Mr Anthony Payne",
                "primaryEmail": null,
                "contactEmails": [
                    {
                        "id": "0ef9a42f-b444-ea11-90fa-005056822d53",
                        "email": "anthony@lonres.com",
                        "description": "",
                        "isPrimary": true,
                        "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
                        "myKfInviteDate": null,
                        "myKfAccountStatusId": null,
                        "myKfAccountStatus": null,
                        "lastWriteTime": "2022-06-18T18:50:26.013Z",
                        "consentMethodId": null,
                        "directMarketingConsentId": null,
                        "isDomainPrivate": false
                    }
                ],
                "visibilityLevel": 0,
                "semiformalSalutation": "Mr Payne",
                "personalWealthId": "094d1d04-e1f7-45f8-a1f7-5de9ec11930a",
                "contactPortalAccounts": [
                    {
                        "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
                        "accountId": "256c0d08-2608-4700-8ab9-f5dcea979bfc",
                        "portalAccountName": "Abigail Carter",
                        "email": "anthony@lonres.com",
                        "createdByUserId": "a220a1ff-8c6e-d242-8151-f653de81fcc3",
                        "accountTypeId": "940bd388-2d0e-4c8e-bd71-b0a6b4df1aa2",
                        "inviteSentTime": "2024-05-20T08:51:55.122Z",
                        "lastLoginTime": "2024-05-20T09:39:35.948Z",
                        "companyContactPortalAccess": []
                    }
                ]
            },
            "residentialAddressTypeId": "0d561d04-e1f7-45f8-a1f7-5de9ec11930a",
            "consentMethodId": "38561d04-e1f7-45f8-a1f7-5de9ec11930a",
            "directMarketingConsentId": "3a561d04-e1f7-45f8-a1f7-5de9ec12952a"
        },
        {
            "id": "51d2a2d5-b544-ea11-90fa-005056822d53",
            "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
            "addressId": "fef10266-31c1-e611-80cc-005056820a11",
            "isPrimary": true,
            "isCorrespondenceConfidential": false,
            "address": {
                "id": "fef10266-31c1-e611-80cc-005056820a11",
                "countryId": "714a1d04-e1f7-45f8-a1f7-5de9ec11930a",
                "addressFormId": "71cf4d03-cdcb-e911-90f5-005056822d53",
                "propertyName": "",
                "propertyNumber": "37",
                "line1": "",
                "line2": "Battersea Square",
                "line3": "",
                "postcode": "SW11 3RA",
                "city": "London",
                "county": "",
                "longitude": -0.1753,
                "latitude": 51.4746,
                "udprnKey": "23927680",
                "umrrnKey": null,
                "uprnKey": "10008158200",
                "shortAddress": "37 Battersea Square, London, SW11 3RA",
                "shortAddressFormatted": "37 Battersea Square, London, SW11 3RA",
                "visibilityLevel": 0
            },
            "creationTime": "2016-11-10T12:31:37.000Z",
            "contact": {
                "id": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
                "title": "Mr",
                "firstName": "Anthony",
                "lastName": "Payne",
                "cddWarningFlag": false,
                "isDeceased": false,
                "isProspect": false,
                "isLockedToNegotiators": false,
                "agreementName": "Mr Anthony Payne",
                "primaryEmail": null,
                "contactEmails": [
                    {
                        "id": "0ef9a42f-b444-ea11-90fa-005056822d53",
                        "email": "anthony@lonres.com",
                        "description": "",
                        "isPrimary": true,
                        "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
                        "myKfInviteDate": null,
                        "myKfAccountStatusId": null,
                        "myKfAccountStatus": null,
                        "lastWriteTime": "2022-06-18T18:50:26.013Z",
                        "consentMethodId": null,
                        "directMarketingConsentId": null,
                        "isDomainPrivate": false
                    }
                ],
                "visibilityLevel": 0,
                "semiformalSalutation": "Mr Payne",
                "personalWealthId": "094d1d04-e1f7-45f8-a1f7-5de9ec11930a",
                "contactPortalAccounts": [
                    {
                        "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
                        "accountId": "256c0d08-2608-4700-8ab9-f5dcea979bfc",
                        "portalAccountName": "Abigail Carter",
                        "email": "anthony@lonres.com",
                        "createdByUserId": "a220a1ff-8c6e-d242-8151-f653de81fcc3",
                        "accountTypeId": "940bd388-2d0e-4c8e-bd71-b0a6b4df1aa2",
                        "inviteSentTime": "2024-05-20T08:51:55.122Z",
                        "lastLoginTime": "2024-05-20T09:39:35.948Z",
                        "companyContactPortalAccess": []
                    }
                ]
            },
            "residentialAddressTypeId": "0c561d04-e1f7-45f8-a1f7-5de9ec11930a",
            "consentMethodId": "38561d04-e1f7-45f8-a1f7-5de9ec11930a",
            "directMarketingConsentId": "3a561d04-e1f7-45f8-a1f7-5de9ec12952a"
        }
    ],
    "companyContactNotes": [],
    "contactCompanyAddresses": [],
    "contactBusinessHistory": [],
    "referralsCount": 1,
    "version": 126,
    "alternativeTitle": null,
    "alternativeFirstName": null,
    "alternativeLastName": null,
    "hasCurrentActivitiesOrRequirements": true,
    "createdByUserId": null,
    "lastModifiedByUserId": "1f9ff10d-9a81-47cb-aae0-51d9f74ba015",
    "lastModifiedByUser": {
        "id": "1f9ff10d-9a81-47cb-aae0-51d9f74ba015",
        "firstName": "Aneela",
        "lastName": "Ahmed",
        "departmentId": "aa9d04a9-5602-4a8b-a7e2-d113b11c2adb",
        "department": {
            "id": "aa9d04a9-5602-4a8b-a7e2-d113b11c2adb",
            "name": "Digital"
        },
        "business": {
            "id": "810ae70d-3d0d-e611-82fe-501ac503c095",
            "name": "Knight Frank LLP"
        },
        "emailAddress": "aneela.ahmed@knightfrank.com",
        "divisionId": "2d4c1d04-e1f7-45f8-a1f7-5de9ec11930a",
        "division": {
            "id": "2d4c1d04-e1f7-45f8-a1f7-5de9ec11930a",
            "code": "BusinessServices",
            "enumTypeId": "174b1d04-e1f7-45f8-a1f7-5de9ec11930a"
        },
        "telephoneNumber": "+44 207 861 5263",
        "mobileNumber": null,
        "employeeNumber": "00002196",
        "countryId": "714a1d04-e1f7-45f8-a1f7-5de9ec11930a",
        "jobRole": "Associate, Senior Software Engineer",
        "active": true,
        "callbackFrequencyId": null,
        "isConfirmedByAttendee": null
    },
    "creationTime": "2016-11-10T12:31:37.000Z",
    "lastWriteTime": "2025-01-14T20:47:16.716Z",
    "mainNegotiator": {
        "id": "1f9ff10d-9a81-47cb-aae0-51d9f74ba015",
        "firstName": "Aneela",
        "lastName": "Ahmed",
        "departmentId": "aa9d04a9-5602-4a8b-a7e2-d113b11c2adb",
        "department": {
            "id": "aa9d04a9-5602-4a8b-a7e2-d113b11c2adb",
            "name": "Digital"
        },
        "business": {
            "id": "810ae70d-3d0d-e611-82fe-501ac503c095",
            "name": "Knight Frank LLP"
        },
        "emailAddress": "aneela.ahmed@knightfrank.com",
        "divisionId": "2d4c1d04-e1f7-45f8-a1f7-5de9ec11930a",
        "division": {
            "id": "2d4c1d04-e1f7-45f8-a1f7-5de9ec11930a",
            "code": "BusinessServices",
            "enumTypeId": "174b1d04-e1f7-45f8-a1f7-5de9ec11930a"
        },
        "telephoneNumber": "+44 207 861 5263",
        "mobileNumber": null,
        "employeeNumber": "00002196",
        "countryId": "714a1d04-e1f7-45f8-a1f7-5de9ec11930a",
        "jobRole": "Associate, Senior Software Engineer",
        "active": true,
        "callbackFrequencyId": null,
        "isConfirmedByAttendee": null
    },
    "visibilityLevel": "Visible",
    "isDeceased": false,
    "isProspect": false,
    "isRetired": false,
    "isAvailableForRequestAccess": false,
    "fairProcessingNoticeId": "3d561d04-e1f7-45f8-a1f7-5de9ec11930a",
    "consentSummary": {
        "emailMarketingConsent": true,
        "postalMarketingConsent": false,
        "consentingIncomplete": false
    },
    "domicileRegionId": null,
    "domicileCountryId": null,
    "sourceOfIncomeId": null,
    "accessRequestCount": 0,
    "lastAccessRequest": null,
    "agreementName": "Mr Anthony Payne",
    "qubeSynchronized": false,
    "consentMethodId": "39561d04-e1f7-45f8-a1f7-5de9ec11930a",
    "directMarketingConsentId": "3a561d04-e1f7-45f8-a1f7-5de9ec11961a",
    "cddValidity": null,
    "hasNda": false,
    "contactPortalAccount": {
        "contactId": "203d45a4-fcf9-4617-bf1c-e882f83437d2",
        "accountId": "256c0d08-2608-4700-8ab9-f5dcea979bfc",
        "portalAccountName": "Abigail Carter",
        "email": "anthony@lonres.com",
        "createdByUserId": "a220a1ff-8c6e-d242-8151-f653de81fcc3",
        "accountTypeId": "940bd388-2d0e-4c8e-bd71-b0a6b4df1aa2",
        "inviteSentTime": "2024-05-20T08:51:55.122Z",
        "lastLoginTime": "2024-05-20T09:39:35.948Z",
        "companyContactPortalAccess": []
    },
    "isCapitalMarketsOrCommercialAgency": true,
    "isLockedToNegotiators": false
}
@endjson