@startuml

actor "Hub User" as user
participant Hub as hub
database HUbDb as hubdb
queue "Service Bus" as bus
participant "Filter Service" as svc
participant "NorthStar CRM" as ns


user -> hub ++ #gold : New/Update Contact
  hub -> hubdb : Save Contact
hub --> user  
  hub -> bus : Publish Contact
  bus -> svc : Subscribe Contact
  Group #pink NorthStar Contact
    svc -> ns 
    ns -> svc : ID
  end
  
  svc -> bus : Publish Contact
  bus -> hub
  hub -> hubdb : Update Contact

@enduml
