@startuml

start
  Group Hub
    : User Creates or Updates a contact;
    : Hub saves contact informaiton into database;
    : Hub puts contact onto the service bus;
  EndGroup

  Group Service Bus
    :Pass Service Request;
  Endgroup

  Group Filter Service
    : Get Contact from service bus;
    : Compare contact with Rules;
    if (NorthStar Contact?) then (TRUE)
      : Pass Contact to NorthStar;
      : Update Contact with NorthStar ID;
    endif
    : Publish Contact onto Service Bus;
  EndGroup

  Group Service Bus
    :Pass Service Response;
  Endgroup

  Group Hub
    : Get Contact from Service Bus;
    : Update Contact in Hub DB;
  EndGroup

stop

@enduml
