@startjson Contact Request
{  
    "Id": "91ac745e-020a-11e6-8d22-5e5517507c66",  
    "Title": "Mr",  
    "FirstName": "Tyrone",  
    "LastName": "Johnston",  
    "FormalSalutation": "Mr Tyrone", 
    "SemiformalSalutation": "Tyrone",  
    "InformalSalutation": null,  
    "PersonalSalutation": null,  
    "EnvelopeSalutation": "Mr Tyrone",  
    "DefaultSalutationId": "574f1d04-e1f7-45f8-a1f7-5de9ec11930a",  
    "Negotiators": null,  
    "CompaniesContacts": null,  
    "NationalityId": null,  
    "IsPodDoNotCall": null,  
    "IsSuperRichAdvisor": null,  
    "SuperRichProfile": null,  
    "ImportantInformation": null,  
    "IsSensitive": null,  
    "SourceId": null,  
    "PersonalWealthId": null,  
    "PropertyInterests": null,  
    "ContactTypes": [    
        {      
            "Id": "1146e26b-99d1-ef11-a874-000d3ab74999",      
            "ContactId": "91ac745e-020a-11e6-8d22-5e5517507c66",      
            "EnumTypeItemId": "024d1d04-e1f7-45f8-a1f7-5de9ec11930a"    
        }  
    ],  
    "PropertyTypeInterests": null,  
    "ProfessionId": "dcfa04da-2e7e-e911-a816-000d3ab8dca4",  
    "ProfessionText": null,  
    "AgeBandId": null,  
    "ApproxBirthDate": null,  
    "TwitterUrl": null,  
    "LinkedInUrl": null,  
    "WebsiteUrl": null,  
    "CddWarningFlag": false,  
    "ContactRelationships": null,  
    "ContactPhones": null,  
    "ContactEmails": null,  
    "Notes": null,  
    "ContactAddresses": null,  
    "CompanyContactNotes": null,  
    "ContactCompanyAddresses": null,  
    "ContactBusinessHistory": null,  
    "ReferralsCount": null,  
    "Version": 0,  
    "AlternativeTitle": null,  
    "AlternativeFirstName": null, 
    "AlternativeLastName": null,  
    "HasCurrentActivitiesOrRequirements": false,  
    "CreatedByUserId": null,  
    "LastModifiedByUserId": null,  
    "LastModifiedByUser": null,  
    "CreationTime": "2025-01-13T10:30:36.93+00:00",  
    "LastWriteTime": "2025-01-13T10:30:36.93+00:00",  
    "MainNegotiator": null,  
    "VisibilityLevel": 0,  
    "IsDeceased": false,  
    "IsProspect": false,  
    "IsRetired": false,  
    "IsAvailableForRequestAccess": false,  
    "FairProcessingNoticeId": "3f561d04-e1f7-45f8-a1f7-5de9ec11930a",  
    "ConsentSummary": null,  
    "DomicileRegionId": null,  
    "DomicileCountryId": null,  
    "SourceOfIncomeId": null,  
    "AccessRequestCount": null,  
    "LastAccessRequest": null,  
    "AgreementName": null,  
    "QubeSynchronized": false,  
    "ConsentMethodId": null,  
    "DirectMarketingConsentId": null,  
    "CddValidity": null,  "HasNda": false,  
    "ContactPortalAccount": null,  
    "IsCapitalMarketsOrCommercialAgency": null, 
    "IsLockedToNegotiators": false
}
@endjson