@startuml System
!include <C4/C4_Container>
!include <azure/AzureCommon>
!include <azure/Integration/AzureServiceBusTopic>

LAYOUT_LEFT_RIGHT()

AddElementTag("microService", $shape=EightSidedShape(), $fontColor="white", $legendText="micro service\neight sided")
AddElementTag("storage", $shape=RoundedBoxShape(), $fontColor="white")


System_Boundary(c1, "Knight Frank") {
    System(hub, "Hub, Property Transaction System") 

    System_Boundary(auth, "Managed Identity") {
        System(app, "Filter Service", "Filters Contacts ", $tags = "microService")  
        AzureServiceBusTopic(toNS, "New\Updated Contacts", "Integration")
        AzureServiceBusTopic(fromNS, "Processed Contacts", "Integration")

    }

    SystemDb(hubDb, "Hub DB", "Transaction Managemnt Storage", $tags = "storage")
    System_Ext(ns, "NorthStar", "NorthStar CRM")
}


Person( user, User, "A User")


Rel(user, hub, "Interact with Contact", "Https")

Rel(hub, hubDb, "Update Contact")
Rel(hub, toNS, "Hub Publish")
Rel(hub, fromNS, "Hub Subscribe")
Rel_U(app, fromNS, "N* Publish Contact")
Rel_U(app, toNS, "N* Subscribe")

Rel(app, ns, "Filtered Contact")
Rel(ns, app, "CRM record Id")

@enduml