@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/EIP-PlantUML/main/dist/EIP-PlantUML.puml
!include <C4/C4_Component>
AddElementTag("storage", $shape=RoundedBoxShape(), $fontColor="white")
LAYOUT_TOP_DOWN()

MessageEndpoint( ep_client, "Client Request" )
Message( cln_req, "Request")
Message( svc_req, "Request")
MessageEndpoint(ep_svc_req, "Service Request" )

System_Boundary(c1, "Domain") {
    SelectiveConsumer(reqval, "Validation")
    MessageTranslator( req2con, "Request to Canonical")
    MessageTranslator( con2svc, "Canonical to Service")
    Message( con, "Canonical")

    ProcessManager( proc, "Process")

    Message( conr, "Canonical")
    MessageTranslator( conr2svc, "Canonical to Response")
    MessageTranslator( svc2conr, "Service Response to Canonical")
    SelectiveConsumer(resval, "Validation")

    con -- proc
    proc -- conr
}

MessageEndpoint( ep_svc_res, "Service Response" )
Message( cln_res, "Response")
Message( svc_res, "Response")
MessageEndpoint(ep_cln_res, "Client Response" )

ep_client -> cln_req
cln_req -> reqval
reqval -> req2con
req2con -> con
con -> con2svc
con2svc -> svc_req
svc_req -> ep_svc_req

cln_req -[hidden]-> cln_res

ep_cln_res <- cln_res
cln_res <- conr2svc
conr2svc <- conr
conr <- svc2conr
svc2conr <- resval
resval <- svc_res
svc_res <- ep_svc_res

@enduml
